/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Abstract.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group position={[-0.33, -1.1, 0.51]} />
        <group position={[6.29, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <group position={[0, 1.39, 0]} />
        <group position={[-2.21, -2.26, -1.77]} />
        <group position={[0.47, 0.07, 0]} />
        <mesh geometry={nodes.Plane099.geometry} material={nodes.Plane099.material} rotation={[0.94, 0.53, -2.18]} />
        <mesh geometry={nodes.Plane098.geometry} material={nodes.Plane098.material} rotation={[0.97, 0.44, -2.13]} />
        <mesh geometry={nodes.Plane097.geometry} material={nodes.Plane097.material} rotation={[1.01, 0.36, -2.08]} />
        <mesh geometry={nodes.Plane096.geometry} material={nodes.Plane096.material} rotation={[1.05, 0.28, -2.02]} />
        <mesh geometry={nodes.Plane095.geometry} material={nodes.Plane095.material} rotation={[1.1, 0.21, -1.96]} />
        <mesh geometry={nodes.Plane094.geometry} material={nodes.Plane094.material} rotation={[1.15, 0.15, -1.89]} />
        <mesh geometry={nodes.Plane093.geometry} material={nodes.Plane093.material} rotation={[1.21, 0.09, -1.82]} />
        <mesh geometry={nodes.Plane092.geometry} material={nodes.Plane092.material} rotation={[1.27, 0.05, -1.74]} />
        <mesh geometry={nodes.Plane091.geometry} material={nodes.Plane091.material} rotation={[1.34, 0.02, -1.66]} />
        <mesh geometry={nodes.Plane090.geometry} material={materials.Material} rotation={[1.41, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Plane089.geometry} material={nodes.Plane089.material} rotation={[1.49, -0.01, -1.48]} />
        <mesh geometry={nodes.Plane088.geometry} material={nodes.Plane088.material} rotation={[1.56, 0, -1.4]} />
        <mesh geometry={nodes.Plane087.geometry} material={nodes.Plane087.material} rotation={[1.63, 0.01, -1.31]} />
        <mesh geometry={nodes.Plane086.geometry} material={nodes.Plane086.material} rotation={[1.69, 0.04, -1.22]} />
        <mesh geometry={nodes.Plane085.geometry} material={nodes.Plane085.material} rotation={[1.75, 0.08, -1.14]} />
        <mesh geometry={nodes.Plane084.geometry} material={nodes.Plane084.material} rotation={[1.81, 0.13, -1.06]} />
        <mesh geometry={nodes.Plane083.geometry} material={nodes.Plane083.material} rotation={[1.86, 0.19, -0.99]} />
        <mesh geometry={nodes.Plane082.geometry} material={nodes.Plane082.material} rotation={[1.9, 0.26, -0.92]} />
        <mesh geometry={nodes.Plane081.geometry} material={nodes.Plane081.material} rotation={[1.93, 0.34, -0.85]} />
        <mesh geometry={nodes.Plane080.geometry} material={nodes.Plane080.material} rotation={[1.95, 0.42, -0.78]} />
        <mesh geometry={nodes.Plane079.geometry} material={nodes.Plane079.material} rotation={[1.97, 0.5, -0.71]} />
        <mesh geometry={nodes.Plane078.geometry} material={nodes.Plane078.material} rotation={[1.97, 0.59, -0.65]} />
        <mesh geometry={nodes.Plane077.geometry} material={nodes.Plane077.material} rotation={[1.96, 0.69, -0.58]} />
        <mesh geometry={nodes.Plane076.geometry} material={nodes.Plane076.material} rotation={[1.94, 0.78, -0.5]} />
        <mesh geometry={nodes.Plane075.geometry} material={nodes.Plane075.material} rotation={[1.9, 0.87, -0.41]} />
        <mesh geometry={nodes.Plane074.geometry} material={nodes.Plane074.material} rotation={[1.83, 0.97, -0.31]} />
        <mesh geometry={nodes.Plane073.geometry} material={nodes.Plane073.material} rotation={[1.72, 1.05, -0.18]} />
        <mesh geometry={nodes.Plane072.geometry} material={nodes.Plane072.material} rotation={[Math.PI / 2, 1.13, 0]} />
        <mesh geometry={nodes.Plane071.geometry} material={nodes.Plane071.material} rotation={[1.35, 1.19, 0.24]} />
        <mesh geometry={nodes.Plane070.geometry} material={nodes.Plane070.material} rotation={[1.05, 1.23, 0.54]} />
        <mesh geometry={nodes.Plane069.geometry} material={nodes.Plane069.material} rotation={[0.72, 1.23, 0.88]} />
        <mesh geometry={nodes.Plane068.geometry} material={nodes.Plane068.material} rotation={[0.43, 1.19, 1.17]} />
        <mesh geometry={nodes.Plane067.geometry} material={nodes.Plane067.material} rotation={[0.19, 1.13, 1.4]} />
        <mesh geometry={nodes.Plane066.geometry} material={nodes.Plane066.material} rotation={[0.02, 1.05, 1.55]} />
        <mesh geometry={nodes.Plane065.geometry} material={nodes.Plane065.material} rotation={[-0.11, 0.96, 1.66]} />
        <mesh geometry={nodes.Plane064.geometry} material={nodes.Plane064.material} rotation={[-0.2, 0.86, 1.73]} />
        <mesh geometry={nodes.Plane063.geometry} material={nodes.Plane063.material} rotation={[-0.28, 0.76, 1.77]} />
        <mesh geometry={nodes.Plane062.geometry} material={nodes.Plane062.material} rotation={[-0.35, 0.67, 1.8]} />
        <mesh geometry={nodes.Plane061.geometry} material={nodes.Plane061.material} rotation={[-0.42, 0.57, 1.8]} />
        <mesh geometry={nodes.Plane060.geometry} material={nodes.Plane060.material} rotation={[-0.47, 0.47, 1.8]} />
        <mesh geometry={nodes.Plane059.geometry} material={nodes.Plane059.material} rotation={[-0.53, 0.38, 1.79]} />
        <mesh geometry={nodes.Plane058.geometry} material={nodes.Plane058.material} rotation={[-0.59, 0.29, 1.76]} />
        <mesh geometry={nodes.Plane057.geometry} material={nodes.Plane057.material} rotation={[-0.65, 0.21, 1.73]} />
        <mesh geometry={nodes.Plane056.geometry} material={nodes.Plane056.material} rotation={[-0.71, 0.13, 1.68]} />
        <mesh geometry={nodes.Plane055.geometry} material={nodes.Plane055.material} rotation={[-0.78, 0.06, 1.63]} />
        <mesh
          geometry={nodes.Plane054.geometry}
          material={nodes.Plane054.material}
          rotation={[-0.85, 0, Math.PI / 2]}
        />
        <mesh geometry={nodes.Plane053.geometry} material={nodes.Plane053.material} rotation={[-0.92, -0.05, 1.5]} />
        <mesh geometry={nodes.Plane052.geometry} material={nodes.Plane052.material} rotation={[-1, -0.1, 1.42]} />
        <mesh geometry={nodes.Plane051.geometry} material={nodes.Plane051.material} rotation={[-1.08, -0.13, 1.34]} />
        <mesh geometry={nodes.Plane050.geometry} material={nodes.Plane050.material} rotation={[-1.16, -0.15, 1.25]} />
        <mesh geometry={nodes.Plane049.geometry} material={nodes.Plane049.material} rotation={[-1.24, -0.15, 1.16]} />
        <mesh geometry={nodes.Plane048.geometry} material={nodes.Plane048.material} rotation={[-1.32, -0.15, 1.07]} />
        <mesh geometry={nodes.Plane047.geometry} material={nodes.Plane047.material} rotation={[-1.39, -0.13, 0.97]} />
        <mesh geometry={nodes.Plane046.geometry} material={nodes.Plane046.material} rotation={[-1.46, -0.1, 0.88]} />
        <mesh geometry={nodes.Plane045.geometry} material={nodes.Plane045.material} rotation={[-1.52, -0.06, 0.79]} />
        <mesh geometry={nodes.Plane044.geometry} material={nodes.Plane044.material} rotation={[-1.57, -0.01, 0.7]} />
        <mesh geometry={nodes.Plane043.geometry} material={nodes.Plane043.material} rotation={[-1.61, 0.05, 0.61]} />
        <mesh geometry={nodes.Plane042.geometry} material={nodes.Plane042.material} rotation={[-1.64, 0.12, 0.53]} />
        <mesh geometry={nodes.Plane041.geometry} material={nodes.Plane041.material} rotation={[-1.66, 0.19, 0.44]} />
        <mesh geometry={nodes.Plane040.geometry} material={nodes.Plane040.material} rotation={[-1.67, 0.26, 0.36]} />
        <mesh geometry={nodes.Plane039.geometry} material={nodes.Plane039.material} rotation={[-1.67, 0.34, 0.28]} />
        <mesh geometry={nodes.Plane038.geometry} material={nodes.Plane038.material} rotation={[-1.65, 0.42, 0.19]} />
        <mesh geometry={nodes.Plane037.geometry} material={nodes.Plane037.material} rotation={[-1.62, 0.49, 0.1]} />
        <mesh
          geometry={nodes.Plane036.geometry}
          material={nodes.Plane036.material}
          rotation={[-Math.PI / 2, 0.57, 0]}
        />
        <mesh geometry={nodes.Plane035.geometry} material={nodes.Plane035.material} rotation={[-1.51, 0.63, -0.11]} />
        <mesh geometry={nodes.Plane034.geometry} material={nodes.Plane034.material} rotation={[-1.42, 0.7, -0.23]} />
        <mesh geometry={nodes.Plane033.geometry} material={nodes.Plane033.material} rotation={[-1.32, 0.75, -0.36]} />
        <mesh geometry={nodes.Plane032.geometry} material={nodes.Plane032.material} rotation={[-1.2, 0.79, -0.5]} />
        <mesh geometry={nodes.Plane031.geometry} material={nodes.Plane031.material} rotation={[-1.06, 0.81, -0.66]} />
        <mesh geometry={nodes.Plane030.geometry} material={nodes.Plane030.material} rotation={[-0.91, 0.81, -0.81]} />
        <mesh geometry={nodes.Plane029.geometry} material={nodes.Plane029.material} rotation={[-0.77, 0.8, -0.97]} />
        <mesh geometry={nodes.Plane028.geometry} material={nodes.Plane028.material} rotation={[-0.62, 0.77, -1.11]} />
        <mesh geometry={nodes.Plane027.geometry} material={nodes.Plane027.material} rotation={[-0.49, 0.72, -1.23]} />
        <mesh geometry={nodes.Plane026.geometry} material={nodes.Plane026.material} rotation={[-0.37, 0.66, -1.34]} />
        <mesh geometry={nodes.Plane025.geometry} material={nodes.Plane025.material} rotation={[-0.26, 0.59, -1.42]} />
        <mesh geometry={nodes.Plane024.geometry} material={nodes.Plane024.material} rotation={[-0.17, 0.52, -1.49]} />
        <mesh geometry={nodes.Plane023.geometry} material={nodes.Plane023.material} rotation={[-0.08, 0.44, -1.54]} />
        <mesh geometry={nodes.Plane022.geometry} material={nodes.Plane022.material} rotation={[0, 0.35, -1.57]} />
        <mesh geometry={nodes.Plane021.geometry} material={nodes.Plane021.material} rotation={[0.07, 0.26, -1.59]} />
        <mesh geometry={nodes.Plane020.geometry} material={nodes.Plane020.material} rotation={[0.14, 0.17, -1.6]} />
        <mesh geometry={nodes.Plane019.geometry} material={nodes.Plane019.material} rotation={[0.21, 0.09, -1.59]} />
        <mesh
          geometry={nodes.Plane018.geometry}
          material={nodes.Plane018.material}
          rotation={[0.28, 0, -Math.PI / 2]}
        />
        <mesh geometry={nodes.Plane017.geometry} material={nodes.Plane017.material} rotation={[0.36, -0.08, -1.54]} />
        <mesh geometry={nodes.Plane016.geometry} material={nodes.Plane016.material} rotation={[0.43, -0.16, -1.5]} />
        <mesh geometry={nodes.Plane015.geometry} material={nodes.Plane015.material} rotation={[0.51, -0.23, -1.44]} />
        <mesh geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} rotation={[0.6, -0.29, -1.38]} />
        <mesh geometry={nodes.Plane013.geometry} material={nodes.Plane013.material} rotation={[0.69, -0.35, -1.3]} />
        <mesh geometry={nodes.Plane012.geometry} material={nodes.Plane012.material} rotation={[0.78, -0.39, -1.21]} />
        <mesh geometry={nodes.Plane011.geometry} material={nodes.Plane011.material} rotation={[0.88, -0.42, -1.11]} />
        <mesh geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} rotation={[0.98, -0.44, -1.01]} />
        <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} rotation={[1.08, -0.44, -0.9]} />
        <mesh geometry={nodes.Plane008.geometry} material={nodes.Plane008.material} rotation={[1.18, -0.43, -0.78]} />
        <mesh geometry={nodes.Plane007.geometry} material={nodes.Plane007.material} rotation={[1.27, -0.4, -0.67]} />
        <mesh geometry={nodes.Plane006.geometry} material={nodes.Plane006.material} rotation={[1.35, -0.37, -0.57]} />
        <mesh geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} rotation={[1.41, -0.32, -0.46]} />
        <mesh geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} rotation={[1.47, -0.27, -0.36]} />
        <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} rotation={[1.51, -0.21, -0.27]} />
        <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} rotation={[1.55, -0.14, -0.18]} />
        <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} rotation={[1.56, -0.07, -0.09]} />
        <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Abstract.glb')
